<a href="https://colab.research.google.com/github/Shritej24c/CNN_practice/blob/master/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow

In [0]:
import keras


Using TensorFlow backend.


In [4]:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(y_test.shape)

x_train shape: (50000, 32, 32, 3)
50000 train samples
(10000, 1)


In [10]:
from keras.models import Sequential
from keras.layers import Convolution2D, Flatten, Dense,  MaxPooling2D, Conv2D, Dropout
from keras.optimizers import SGD, Adam, rmsprop
from keras.datasets import cifar10
from keras.utils import to_categorical
from keras.layers.convolutional import Conv2D


#Datasets
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

ytrain = to_categorical(y_train,10)
ytest = to_categorical(y_test,10)

#Initializing the CNN

model = Sequential()

#Step 1 - Convolutional
model.add(Conv2D(filters=32, kernel_size=(3, 3),input_shape=(32, 32, 3),activation="relu"))
model.add(Conv2D(filters=32, kernel_size=(3,3), padding='same',activation='relu'))

#Step 2 - Pooling
model.add(MaxPooling2D(pool_size=(2, 2)))

#Dropout 

model.add(Dropout(0.25))

#Adding the convolutional layer
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))

model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Dropout(0.25))

#Step 3 - Flatten
model.add(Flatten())


#Step 4 - Dense
model.add(Dense(units=512, activation='relu'))
model.add(Dense(units=10, activation='softmax'))

# compile model
# initiate RMSprop optimizer
opt = rmsprop(lr=0.0001, decay=1e-6)

model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

# fit model
history = model.fit(x_train, ytrain, batch_size=32,validation_data=(x_test, ytest), epochs=100, verbose=0, shuffle=True)
# evaluate the model
_, train_acc = model.evaluate(x_train, ytrain, verbose=0)
_, test_acc = model.evaluate(x_test, ytest, verbose=0)
print('Train: %.3f, Test: %.3f' % (train_acc, test_acc))



Train: 0.998, Test: 0.789


In [3]:
from keras.models import Sequential
from keras.layers import Convolution2D, Flatten, Dense,  MaxPooling2D, Conv2D, Dropout
from keras.optimizers import SGD, Adam, rmsprop, Nadam
from keras.datasets import cifar10
from keras.utils import to_categorical
from keras.layers.convolutional import Conv2D


#Datasets
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

ytrain = to_categorical(y_train,10)
ytest = to_categorical(y_test,10)

#Initializing the CNN

model = Sequential()

#Step 1 - Convolutional
model.add(Conv2D(filters=32, kernel_size=(3, 3),input_shape=(32, 32, 3),activation="relu"))
#model.add(Conv2D(filters=32, kernel_size=(3,3), padding='same',activation='relu'))

#Step 2 - Pooling
model.add(MaxPooling2D(pool_size=(2, 2)))

#Dropout 

model.add(Dropout(0.3))

#Adding the convolutional layer
model.add(Conv2D(32, (3, 3), activation='relu'))
#model.add(Conv2D(64, (3, 3), activation='relu'))

model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Dropout(0.3))

#Step 3 - Flatten
model.add(Flatten())


#Step 4 - Dense
model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=10, activation='softmax'))

# compile model
# initiate RMSprop optimizer
opt = rmsprop(lr=0.0001, decay=1e-6)
optimizer = Nadam(lr=0.002,
                  beta_1=0.9,
                  beta_2=0.999,
                  epsilon=1e-08,
                  schedule_decay=0.004)


model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

# fit model
history = model.fit(x_train, ytrain, batch_size=32,validation_data=(x_test, ytest), epochs=100, verbose=0, shuffle=True)
# evaluate the model
_, train_acc = model.evaluate(x_train, ytrain, verbose=0)
_, test_acc = model.evaluate(x_test, ytest, verbose=0)
print('Train: %.3f, Test: %.3f' % (train_acc, test_acc))



170500096/170498071 [==============================] - 20s 0us/step
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.
Train: 0.901, Test: 0.715


In [4]:
from keras.models import Sequential
from keras.layers import Convolution2D, Flatten, Dense,  MaxPooling2D, Conv2D, Dropout
from keras.optimizers import SGD, Adam, rmsprop, Nadam
from keras.datasets import cifar10
from keras.utils import to_categorical
from keras.layers.convolutional import Conv2D
from keras.regularizers import l2

#Datasets
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

ytrain = to_categorical(y_train,10)
ytest = to_categorical(y_test,10)

#Initializing the CNN classifier 

model = Sequential()

#Step 1 - Convolutional
model.add(Conv2D(filters=32, kernel_size=(3, 3), padding='same', input_shape=(32, 32, 3),activation="relu"))
#model.add(Conv2D(filters=32, kernel_size=(3,3), padding='same',activation='relu'))

#Step 2 - Pooling
model.add(MaxPooling2D(pool_size=(2, 2)))

#Dropout 

model.add(Dropout(0.25))

#Adding the convolutional layer
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
#model.add(Conv2D(64, (3, 3), activation='relu'))

model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Dropout(0.25))

#Step 3 - Flatten
model.add(Flatten())


#Step 4 - Dense
model.add(Dense(units=512, activation='relu'))
model.add(Dense(units=10, activation='softmax'))

# compile model
# initiate RMSprop optimizer
opt = rmsprop(lr=0.0001, decay=1e-6)
optimizer = Nadam(lr=0.002,
                  beta_1=0.9,
                  beta_2=0.999,
                  epsilon=1e-08,
                  schedule_decay=0.004)


model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

# fit model
history = model.fit(x_train, ytrain, batch_size=32, validation_data = (x_test, ytest), epochs=100, verbose=0, shuffle=True)
# evaluate the model
_, train_acc = model.evaluate(x_train, ytrain, verbose=0)
_, test_acc = model.evaluate(x_test, ytest, verbose=0)
print('Train: %.3f' % (train_acc))



Train: 0.988


In [15]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, cohen_kappa_score, roc_auc_score, confusion_matrix
from sklearn.metrics import classification_report
# predict probabilities for test set
yhat_probs = model.predict(x_test, verbose=0)
# predict crisp classes for test set
yhat_classes = model.predict_classes(x_test, verbose=0)
# reduce to 1d array
print(yhat_classes)
yhat_prob = yhat_probs
yhat_class = yhat_classes
 
# accuracy: (tp + tn) / (p + n)
accuracy = accuracy_score(y_test, yhat_classes)
print('Accuracy: %f' % accuracy)
# precision tp / (tp + fp)
#precision = precision_score(y_test, yhat_classes)
#print('Precision: %f' % precision)
# recall: tp / (tp + fn)
#recall = recall_score(y_test, yhat_classes)
#print('Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)

# confusion matrix
matrix = confusion_matrix(y_test, yhat_classes)
report = classification_report(y_test, yhat_classes)
print(matrix)
print(report)

[3 1 8 ... 5 1 7]
Accuracy: 0.754200
[[827  12  31  11  18  10  10  17  46  18]
 [ 24 856   7   5   5   4   9   7  27  56]
 [ 65   2 628  50  86  57  63  30  11   8]
 [ 19   6  56 479  67 220  95  39   6  13]
 [ 17   4  55  32 733  48  42  61   5   3]
 [  9   4  24  91  57 707  47  50   6   5]
 [  6   4  32  28  33  20 869   3   2   3]
 [ 13   0  15  22  43  54  10 836   1   6]
 [ 70  34  16   6  10   6   7   9 825  17]
 [ 49  75  12  14   4   9  10  20  25 782]]
              precision    recall  f1-score   support

           0       0.75      0.83      0.79      1000
           1       0.86      0.86      0.86      1000
           2       0.72      0.63      0.67      1000
           3       0.65      0.48      0.55      1000
           4       0.69      0.73      0.71      1000
           5       0.62      0.71      0.66      1000
           6       0.75      0.87      0.80      1000
           7       0.78      0.84      0.81      1000
           8       0.86      0.82      0.84  

In [18]:
print(test_acc)

0.7542


In [21]:
import numpy as np
recall = np.diag(matrix) / np.sum(matrix, axis = 1)
precision = np.diag(matrix) / np.sum(matrix, axis = 0)
print(recall)
print(precision)
print(np.mean(recall))
print(np.mean(precision))

[0.827 0.856 0.628 0.479 0.733 0.707 0.869 0.836 0.825 0.782]
[0.75250227 0.85857573 0.71689498 0.64905149 0.69412879 0.62290749
 0.74784854 0.77985075 0.86477987 0.85839737]
0.7542000000000001
0.7544937269546279
