<a href="https://colab.research.google.com/github/Shritej24c/CNN_practice/blob/master/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow

In [0]:
import keras


Using TensorFlow backend.


In [0]:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(y_test.shape)

x_train shape: (50000, 32, 32, 3)
50000 train samples
(10000, 1)


In [0]:
from keras.models import Sequential
from keras.layers import Convolution2D, Flatten, Dense,  MaxPooling2D, Conv2D, Dropout
from keras.optimizers import SGD, Adam, rmsprop
from keras.datasets import cifar10
from keras.utils import to_categorical
from keras.layers.convolutional import Conv2D


#Datasets
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

ytrain = to_categorical(y_train,10)
ytest = to_categorical(y_test,10)

#Initializing the CNN

model = Sequential()

#Step 1 - Convolutional
model.add(Conv2D(filters=32, kernel_size=(3, 3),input_shape=(32, 32, 3),activation="relu"))
model.add(Conv2D(filters=32, kernel_size=(3,3), padding='same',activation='relu'))

#Step 2 - Pooling
model.add(MaxPooling2D(pool_size=(2, 2)))

#Dropout 

model.add(Dropout(0.25))

#Adding the convolutional layer
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))

model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Dropout(0.25))

#Step 3 - Flatten
model.add(Flatten())


#Step 4 - Dense
model.add(Dense(units=512, activation='relu'))
model.add(Dense(units=10, activation='softmax'))

# compile model
# initiate RMSprop optimizer
opt = rmsprop(lr=0.0001, decay=1e-6)

model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

# fit model
history = model.fit(x_train, ytrain, batch_size=32,validation_data=(x_test, ytest), epochs=100, verbose=0, shuffle=True)
# evaluate the model
_, train_acc = model.evaluate(x_train, ytrain, verbose=0)
_, test_acc = model.evaluate(x_test, ytest, verbose=0)
print('Train: %.3f, Test: %.3f' % (train_acc, test_acc))



Train: 0.998, Test: 0.789


In [0]:
from keras.models import Sequential
from keras.layers import Convolution2D, Flatten, Dense,  MaxPooling2D, Conv2D, Dropout
from keras.optimizers import SGD, Adam, rmsprop, Nadam
from keras.datasets import cifar10
from keras.utils import to_categorical
from keras.layers.convolutional import Conv2D


#Datasets
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

ytrain = to_categorical(y_train,10)
ytest = to_categorical(y_test,10)

#Initializing the CNN

model = Sequential()

#Step 1 - Convolutional
model.add(Conv2D(filters=32, kernel_size=(3, 3),input_shape=(32, 32, 3),activation="relu"))
#model.add(Conv2D(filters=32, kernel_size=(3,3), padding='same',activation='relu'))

#Step 2 - Pooling
model.add(MaxPooling2D(pool_size=(2, 2)))

#Dropout 

model.add(Dropout(0.3))

#Adding the convolutional layer
model.add(Conv2D(32, (3, 3), activation='relu'))
#model.add(Conv2D(64, (3, 3), activation='relu'))

model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Dropout(0.3))

#Step 3 - Flatten
model.add(Flatten())


#Step 4 - Dense
model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=10, activation='softmax'))

# compile model
# initiate RMSprop optimizer
opt = rmsprop(lr=0.0001, decay=1e-6)
optimizer = Nadam(lr=0.002,
                  beta_1=0.9,
                  beta_2=0.999,
                  epsilon=1e-08,
                  schedule_decay=0.004)


model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

# fit model
history = model.fit(x_train, ytrain, batch_size=32,validation_data=(x_test, ytest), epochs=100, verbose=0, shuffle=True)
# evaluate the model
_, train_acc = model.evaluate(x_train, ytrain, verbose=0)
_, test_acc = model.evaluate(x_test, ytest, verbose=0)
print('Train: %.3f, Test: %.3f' % (train_acc, test_acc))



170500096/170498071 [==============================] - 20s 0us/step
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.
Train: 0.901, Test: 0.715


In [0]:
from keras.models import Sequential
from keras.layers import Flatten, Dense, MaxPooling2D, Dropout
from keras.optimizers import SGD, Adam, rmsprop, Nadam
from keras.datasets import cifar10
from keras.utils import to_categorical
from keras.layers.convolutional import Conv2D
from keras.regularizers import l2

#Datasets
(x_train, y_train), (x_test, y_test) = cifar10.load_data()


input_shape = x_train.shape[1:]
num_classes = 10

ytrain = to_categorical(y_train, num_classes)
ytest = to_categorical(y_test, num_classes)

#Initializing the CNN classifier 

model = Sequential()

#Step 1 - Convolutional
model.add(Conv2D(filters=32, kernel_size=(3, 3), padding='same', input_shape=input_shape, activation="relu"))
#model.add(Conv2D(filters=32, kernel_size=(3,3), padding='same',activation='relu'))

#Step 2 - Pooling
model.add(MaxPooling2D(pool_size=(2, 2)))

#Dropout 

model.add(Dropout(0.25))

#Adding the convolutional layer
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
#model.add(Conv2D(64, (3, 3), activation='relu'))

model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Dropout(0.25))

#Step 3 - Flatten
model.add(Flatten())


#Step 4 - Dense
model.add(Dense(units=512, activation='relu'))
model.add(Dense(units=num_classes, activation='softmax'))


# initiate RMSprop optimizer
opt = rmsprop(lr=0.0001, decay=1e-6)
optimizer = Nadam(lr=0.002,
                  beta_1=0.9,
                  beta_2=0.999,
                  epsilon=1e-08,
                  schedule_decay=0.004)

# compile model
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

# fit model
history = model.fit(x_train, ytrain, batch_size=32, validation_data = (x_test, ytest), epochs=100, verbose=0, shuffle=True)

# evaluate the model
_, train_acc = model.evaluate(x_train, ytrain, verbose=0)
_, test_acc = model.evaluate(x_test, ytest, verbose=0)
print('Train Accuracy : %.3f' % (train_acc))
print('Test Accuracy : %.3f' %(test_acc))

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# predict probabilities for test set
yhat_probs = model.predict(x_test, verbose=0)
# predict crisp classes for test set
yhat_classes = model.predict_classes(x_test, verbose=0)

# confusion matrix
matrix = confusion_matrix(y_test, yhat_classes)
report = classification_report(y_test, yhat_classes)
print('Confusion matrix : \n', matrix)
print(report)




Using TensorFlow backend.


170500096/170498071 [==============================] - 13s 0us/step
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.
Train Accuracy : 0.992
Test Accuracy : 0.748
Confusion matrix : 
 [[812  17  55   9   7   8  15  12  39  26]
 [ 16 838   4   7   6   6  11   4  27  81]
 [ 59   4 686  39  65  56  57  21   7   6]
 [ 20   9  91 501  49 200  60  40   9  21]
 [ 13   5  95  38 671  48  51  66   8   5]
 [ 12   3  63 125  40 685  26  37   2   7]
 [ 10   4  49  27  27  28 840   6   5   4]
 [ 20   3  35  29  38  52   7 801   2  13]
 [ 57  36  24  10   5  10   8   2 827  21]
 [ 39  63   7  11   3  12   4  18  26 817]]
              precision    recall  f1-score   support

           0       0.77      0.81      0.79      1000
           1       0.85      0.84      0.85      1000
           2       0.62      0.69    

In [0]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, cohen_kappa_score, roc_auc_score, confusion_matrix
from sklearn.metrics import classification_report
# predict probabilities for test set
yhat_probs = model.predict(x_test, verbose=0)
# predict crisp classes for test set
yhat_classes = model.predict_classes(x_test, verbose=0)
# reduce to 1d array
print(yhat_classes)
yhat_prob = yhat_probs
yhat_class = yhat_classes
 
# accuracy: (tp + tn) / (p + n)
accuracy = accuracy_score(y_test, yhat_classes)
print('Accuracy: %f' % accuracy)
# precision tp / (tp + fp)
#precision = precision_score(y_test, yhat_classes)
#print('Precision: %f' % precision)
# recall: tp / (tp + fn)
#recall = recall_score(y_test, yhat_classes)
#print('Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)

# confusion matrix
matrix = confusion_matrix(y_test, yhat_classes)
report = classification_report(y_test, yhat_classes)
print('Confusion matrix : \n', matrix)
print(report)

[3 1 8 ... 5 1 7]
Accuracy: 0.754200
[[827  12  31  11  18  10  10  17  46  18]
 [ 24 856   7   5   5   4   9   7  27  56]
 [ 65   2 628  50  86  57  63  30  11   8]
 [ 19   6  56 479  67 220  95  39   6  13]
 [ 17   4  55  32 733  48  42  61   5   3]
 [  9   4  24  91  57 707  47  50   6   5]
 [  6   4  32  28  33  20 869   3   2   3]
 [ 13   0  15  22  43  54  10 836   1   6]
 [ 70  34  16   6  10   6   7   9 825  17]
 [ 49  75  12  14   4   9  10  20  25 782]]
              precision    recall  f1-score   support

           0       0.75      0.83      0.79      1000
           1       0.86      0.86      0.86      1000
           2       0.72      0.63      0.67      1000
           3       0.65      0.48      0.55      1000
           4       0.69      0.73      0.71      1000
           5       0.62      0.71      0.66      1000
           6       0.75      0.87      0.80      1000
           7       0.78      0.84      0.81      1000
           8       0.86      0.82      0.84  

In [0]:
from keras.models import load_model, model_from_json
import h5py

model.save("digit-recognizer\classifier.h5")

In [0]:
print(x_test.shape)
model.summary()


(10000, 32, 32, 3)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 32, 32, 32)        896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 16, 16, 32)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 16, 16, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 16, 16, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 8, 8, 32)          0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 8, 8, 32)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 2048)              0 

In [0]:
loaded_model = load_model('digit-recognizer\classifier.h5')

loaded_model.summary()

import random

y_prob = loaded_model.predict(x_test[0:2,:,:,:], verbose=0)

y_class = loaded_model.predict_classes(x_test[0:2,:,:,:], verbose=0)

print(y_prob)
print(y_class)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 32, 32, 32)        896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 16, 16, 32)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 16, 16, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 16, 16, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 8, 8, 32)          0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 8, 8, 32)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 2048)              0         
__________

In [0]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import io

from google.colab import files

uploaded = files.upload()



In [0]:
print(test_acc)

0.7542


In [0]:
import numpy as np
recall = np.diag(matrix) / np.sum(matrix, axis = 1)
precision = np.diag(matrix) / np.sum(matrix, axis = 0)
print(recall)
print(precision)
print(np.mean(recall))
print(np.mean(precision))

[0.827 0.856 0.628 0.479 0.733 0.707 0.869 0.836 0.825 0.782]
[0.75250227 0.85857573 0.71689498 0.64905149 0.69412879 0.62290749
 0.74784854 0.77985075 0.86477987 0.85839737]
0.7542000000000001
0.7544937269546279


In [0]:
print(model.summary())

NameError: ignored

In [0]:
4+4

8

In [0]:
import pandas as pd

train_data = pd.read_csv("digit-recognizer\train.csv")

FileNotFoundError: ignored

In [0]:
import os
print(os.path())

TypeError: ignored

In [48]:
import pandas as pd
import numpy as np
from keras.utils import to_categorical 
from keras.layers.convolutional import Conv1D
from keras.layers import Dense, MaxPooling1D, Dropout, Flatten
from keras.models import Sequential 
from keras.optimizers import SGD, Adam, rmsprop, Nadam, Adadelta
from sklearn.model_selection import train_test_split

num_classes = 10

train_data = pd.read_csv('https://raw.githubusercontent.com/Shritej24c/CNN_practice/master/digit-recognizer/train.csv')

test_data = pd.read_csv('https://raw.githubusercontent.com/Shritej24c/CNN_practice/master/digit-recognizer/test.csv')


train = np.array(train_data)
test = np.array(test_data)

ytrain = train[:,0]
xtrain = np.reshape(train[:,1:],(42000,28,28))

xtrain, xtest, ytrain, y_test = train_test_split(xtrain, ytrain, test_size = 0.25, random_state = 23)

ytrain = to_categorical(ytrain)
ytest =  to_categorical(y_test)

input_shape = (28,28)


#Initializing the CNN classifier 

model = Sequential()

#Step 1 - Convolutional
model.add(Conv1D(filters=32, kernel_size=3, padding='same', input_shape=input_shape, activation="relu"))
model.add(Conv1D(filters=32, kernel_size=3, padding='same',activation='relu'))

#Step 2 - Pooling
model.add(MaxPooling1D(pool_size=2))

#Dropout 

model.add(Dropout(0.25))

#Adding the convolutional layer
model.add(Conv1D(32, 3, activation='relu', padding='same'))
model.add(Conv1D(64, 3, activation='relu', padding='same'))

model.add(MaxPooling1D(pool_size=2))

model.add(Dropout(0.25))

#Step 3 - Flatten
model.add(Flatten())


#Step 4 - Dense
model.add(Dense(units=512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(units=num_classes, activation='softmax'))


# initiate RMSprop optimizer
opt = rmsprop(lr=0.0001, decay=1e-6)
optimizer = Nadam(lr=0.002,
                  beta_1=0.9,
                  beta_2=0.999,
                  epsilon=1e-08,
                  schedule_decay=0.004)

# compile model
model.compile(loss='categorical_crossentropy', optimizer=Adadelta(), metrics=['accuracy'])

xtrain = xtrain.astype('float32')
xtest = xtest.astype('float32')
xtrain /= 255
xtest /= 255

# fit model
history = model.fit(xtrain, ytrain, batch_size=32, validation_data = (xtest, ytest), epochs=100, verbose=0, shuffle=True)

# evaluate the model
_, train_acc = model.evaluate(xtrain, ytrain, verbose=0)
_, test_acc = model.evaluate(xtest, ytest, verbose=0)
print('Train Accuracy : %.3f' % (train_acc))
print('Test Accuracy : %.3f' %(test_acc))

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# predict probabilities for test set
yhat_probs = model.predict(xtest, verbose=0)
# predict crisp classes for test set
yhat_classes = model.predict_classes(xtest, verbose=0)

# confusion matrix
matrix = confusion_matrix(y_test, yhat_classes)
report = classification_report(y_test, yhat_classes)
print('Confusion matrix : \n', matrix)
print(report)


Train Accuracy : 1.000
Test Accuracy : 0.990
Confusion matrix : 
 [[1049    0    0    0    0    0    0    0    0    1]
 [   0 1155    0    1    0    0    2    1    2    0]
 [   1    1 1047    4    0    0    0    2    3    0]
 [   0    0    1 1076    0    1    0    1    1    4]
 [   0    1    0    0 1020    0    1    2    3   12]
 [   0    0    0   10    0  940    0    1    0    1]
 [   0    0    1    0    2    1 1037    0    0    0]
 [   0    3    2    0    0    0    0 1066    0    2]
 [   1    2    3    5    2    1    3    1  980    5]
 [   0    0    0    1    3    3    0    3    0 1029]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1050
           1       0.99      0.99      0.99      1161
           2       0.99      0.99      0.99      1058
           3       0.98      0.99      0.99      1084
           4       0.99      0.98      0.99      1039
           5       0.99      0.99      0.99       952
           6       0.99 

In [0]:
test = test.reshape(28000,28,28)

pred = model.predict_classes(test,verbose=0)

import numpy as np

df = np.zeros((len(pred),2))

for i in range(len(pred)):
  df[i] = np.array([i+1, pred[i]])
  
import csv

with open('sample_submission_1.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(df)

csvFile.close()
  

In [0]:
from google.colab import files

files.download('sample_submission_1.csv')

In [0]:
print(ytest.shape)
print(yhat_classes.shape)
print(yhat_probs.shape)
test = np.reshape(test, (28000,28,28))
# predict probabilities for test set
pred_probs = model.predict(xtest, verbose=0)
# predict crisp classes for test set
pred_classes = model.predict_classes(xtest, verbose=0)
print(pred_classes.shape)

(10500, 10)
(10500,)
(10500, 10)
(10500,)


In [0]:
print(ytrain[11])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical

train_data = pd.read_csv('https://raw.githubusercontent.com/Shritej24c/CNN_practice/master/digit-recognizer/train.csv')

test_data = pd.read_csv('https://raw.githubusercontent.com/Shritej24c/CNN_practice/master/digit-recognizer/test.csv')


train = np.array(train_data)
test = np.array(test_data)

ytrain = train[:,0]
xtrain = np.reshape(train[:,1:],(42000,28,28))

xtrain, xtest, ytrain, ytest = train_test_split(xtrain, ytrain, test_size = 0.25, random_state = 23)

print(ytrain.shape)
ytrain = to_categorical(ytrain)


print(ytrain.shape)
print(xtrain.shape)

(31500,)
(31500, 10)
(31500, 28, 28)


In [39]:
import numpy as np
re = np.zeros((3,3))
r = np.array([2,33])

print(r)

re[0] = r
print(re)

df = pd.DataFrame(re)

df.to_csv("lame.csv", sep="\t",index=False)
re

[ 2 33]
[[ 2. 33.]
 [ 0.  0.]]


In [0]:
from google.colab import files

files.download('lame.csv')

In [0]:
import csv



with open('person.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(re)

csvFile.close()

In [0]:
from google.colab import files

files.download('person.csv')

In [44]:
head = ["data", 'label']

re[0] = head
re[1] = r

print(re)

ValueError: ignored